In [1]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings("ignore")


In [2]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, classification_report


In [3]:
import route_optimization as ro

In [4]:
flights_df = pd.read_csv("data/Flight_Database.csv")
weather_data = pd.read_csv("data/M1_final.csv")
cities_weather = pd.read_csv("data/weather_data_cities.csv")
cities_time = pd.read_csv("data/Cities_FlightDuration_Mins.csv")


In [5]:
label_mapping = {
    " Fair / Windy ": 3,
    " Fair ": 1,
    " Light Rain / Windy ": 7,
    " Partly Cloudy ": 2,
    " Mostly Cloudy ": 2,
    " Cloudy ": 5,
    " Light Rain ": 6,
    " Mostly Cloudy / Windy ": 8,
    " Partly Cloudy / Windy ": 5,
    " Light Snow / Windy ": 4,
    " Cloudy / Windy ": 5,
    " Light Drizzle ": 5,
    " Rain ": 6,
    " Heavy Rain ": 9,
    " Fog ": 8,
    " Wintry Mix ": 4,
    " Light Freezing Rain ": 8,
    " Light Snow ": 3,
    " Wintry Mix / Windy ": 4,
    " Fog / Windy ": 8,
    " Light Drizzle / Windy ": 6,
    " Rain / Windy ": 7,
    " Drizzle and Fog ": 9,
    " Snow ": 3,
    " Heavy Rain / Windy ": 10,
}


In [6]:
weather_data["SafetyLevel"] = weather_data[" Condition "].map(label_mapping)

In [7]:
features = [
    "Temperature",
    "Humidity",
    "Wind Speed",
    "Pressure",
]
X = weather_data[features]
y = weather_data["SafetyLevel"]


In [8]:
x_train, x_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [9]:
logreg = LogisticRegression()
logreg.fit(x_train, y_train)
y_pred = logreg.predict(x_test)
print("Logistic Regression")
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


Logistic Regression
[[ 162  832    4    0    0    2    0    7    0    0]
 [  78 2366    0    0    3   19    0    1    0    0]
 [   6   26  114    0    0    0    0   53    0    0]
 [   2   17    3    0    0    0    0    0    0    0]
 [  16  959   27    0    0  110    0  110    0    0]
 [  63  245    0    0    0  132    0    7    0    0]
 [   0   20    0    0    0    0    0   43    0    0]
 [   4   61   27    0    0   17    0  215    0    0]
 [   0    2    0    0    0   10    0    0    0    0]
 [   0    0    0    0    0    0    0    1    0    0]]
              precision    recall  f1-score   support

           1       0.49      0.16      0.24      1007
           2       0.52      0.96      0.68      2467
           3       0.65      0.57      0.61       199
           4       0.00      0.00      0.00        22
           5       0.00      0.00      0.00      1222
           6       0.46      0.30      0.36       447
           7       0.00      0.00      0.00        63
           8    

In [10]:
svc = SVC()
svc.fit(x_train, y_train)
y_pred = svc.predict(x_test)
print("Support Vector Machine")
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


Support Vector Machine
[[ 215  770   13    0    0    6    0    3    0    0]
 [ 103 2281    0    0   28   41    0   14    0    0]
 [  18   15   91    0   14    3    0   58    0    0]
 [   0   12    1    0    7    2    0    0    0    0]
 [  19  840   14    0  167   80    3   99    0    0]
 [   0  149    0    0   83  208    0    7    0    0]
 [   0    0    0    0   25    6   26    6    0    0]
 [   0   30    3    0   37   20    0  234    0    0]
 [   0    0    0    0    2   10    0    0    0    0]
 [   0    0    0    0    0    0    1    0    0    0]]
              precision    recall  f1-score   support

           1       0.61      0.21      0.32      1007
           2       0.56      0.92      0.70      2467
           3       0.75      0.46      0.57       199
           4       0.00      0.00      0.00        22
           5       0.46      0.14      0.21      1222
           6       0.55      0.47      0.51       447
           7       0.87      0.41      0.56        63
           8 

In [11]:
dt = DecisionTreeClassifier()
dt.fit(x_train, y_train)
y_pred = dt.predict(x_test)
print("Decision Tree")
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


Decision Tree
[[1007    0    0    0    0    0    0    0    0    0]
 [   1 2457    0    0    9    0    0    0    0    0]
 [   0    0  197    0    2    0    0    0    0    0]
 [   0    0    0   22    0    0    0    0    0    0]
 [   0    2    1    0 1216    3    0    0    0    0]
 [   0    0    0    0    1  445    1    0    0    0]
 [   0    0    0    0    0    0   63    0    0    0]
 [   0    0    1    0    0    0    0  323    0    0]
 [   0    0    0    0    0    0    0    0   12    0]
 [   0    0    0    0    0    0    0    0    0    1]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00      1007
           2       1.00      1.00      1.00      2467
           3       0.99      0.99      0.99       199
           4       1.00      1.00      1.00        22
           5       0.99      1.00      0.99      1222
           6       0.99      1.00      0.99       447
           7       0.98      1.00      0.99        63
           8       1.0

In [12]:
le = LabelEncoder()
df = pd.read_csv("data/MLMachineFiles.csv")
df["Warranty Status"] = le.fit_transform(df["Warranty Status"])
df["Company"] = le.fit_transform(df["Company"])

X = df[["Days Since Servicing", "Warranty Status", "Days Since Purchase", "Company"]]
y = df["Status"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

serviceModel = DecisionTreeClassifier(random_state=42)
serviceModel.fit(X_train, y_train)

y_pred = serviceModel.predict(X_test)
print("Service Model")
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


Service Model
[[216   0   0   0   0   7]
 [  3  30   0   0   0   0]
 [  0   0 657   1   6   0]
 [  0   0   1 272   0   0]
 [  0   0   3   0 408   6]
 [  5   0   0   0   5 380]]
                           precision    recall  f1-score   support

      Delay for servicing       0.96      0.97      0.97       223
                   Ground       1.00      0.91      0.95        33
    No servicing required       0.99      0.99      0.99       664
                  Perfect       1.00      1.00      1.00       273
    Service required soon       0.97      0.98      0.98       417
Urgent Servicing Required       0.97      0.97      0.97       390

                 accuracy                           0.98      2000
                macro avg       0.98      0.97      0.98      2000
             weighted avg       0.98      0.98      0.98      2000



In [13]:
filename = "data\Cities_FlightDuration_Mins.csv"
nodes, graph_data = ro.load_data(filename)
G = ro.create_graph(nodes, graph_data)


In [14]:
def safetyCalculator(city, time, model=dt):
    time_obj = datetime.strptime(time, "%H:%M")
    minute = time_obj.minute
    if minute >= 30:
        time_obj += timedelta(hours=1)
    time_obj = time_obj.replace(minute=0, second=0)
    time = time_obj.strftime("%H:%M")

    string_stats = cities_weather[cities_weather["City"] == city][time].values[0]
    string_stats = string_stats.replace("'", "").replace("{", "").replace("}", "")
    key_value_pairs = string_stats.split(", ")
    input_stats = {}
    for pair in key_value_pairs:
        key, value = pair.split(": ")
        input_stats[key] = float(value)

    input_array = np.array([input_stats[feature] for feature in features]).reshape(
        1, -1
    )
    prediction = model.predict(input_array)

    return prediction[0]


In [15]:
def unsafeCities(DEP_City, ARR_City, DEP_Time, G):
    unsafe_nodes = []
    safe_nodes = []
    for node in G.nodes():
        if node == DEP_City:
            if safetyCalculator(DEP_City, DEP_Time) >= 5:
                print("Delay takeoff")
        elif node == ARR_City:
            continue
        else:
            time_from_dep_2_node = cities_time[cities_time["City"] == DEP_City][
                node
            ].values[0]
            time_of_day = (
                datetime.strptime(DEP_Time, "%H:%M")
                + timedelta(minutes=int(time_from_dep_2_node))
            ).strftime("%H:%M")
            if safetyCalculator(node, time_of_day) >= 6:
                print(node, "at", time_of_day, ":", safetyCalculator(node, time_of_day))
                unsafe_nodes.append(node)
            else:
                print(node, "at", time_of_day, ":", safetyCalculator(node, time_of_day))
                safe_nodes.append(node)

    print("Unsafe cities from", DEP_City, "to", ARR_City, ":", unsafe_nodes)
    return unsafe_nodes, safe_nodes


In [16]:
import tkinter as tk
from tkinter import ttk
from customtkinter import *


def displaySafetyLevels(dep_city, dep_time, arr_city, RouteFrame):
    table_frame = CTkScrollableFrame(
        master=RouteFrame,
        width=200,
        height=250,
        orientation="vertical",
        border_color="white",
        border_width=2,
        fg_color="black",
    )

    # Create labels for headers
    header_city = CTkLabel(
        master=table_frame, text="City", font=("Arial", 14), text_color="white"
    )
    header_city.grid(row=0, column=0, padx=10)

    header_safety = CTkLabel(
        master=table_frame, text="Safety", font=("Arial", 14), text_color="white"
    )
    header_safety.grid(row=0, column=1, padx=10)

    row_index = 1
    for city in G.nodes():
        time_of_day = (
            datetime.strptime(dep_time, "%H:%M")
            + timedelta(
                minutes=int(
                    cities_time[cities_time["City"] == dep_city][city].values[0]
                )
            )
        ).strftime("%H:%M")
        safety_level = safetyCalculator(city, time_of_day)
        if city == dep_city:
            if safety_level >= 5:
                color = "#ff8099"
            else:
                color = "#80ff88"
        else:
            if safety_level >= 6:
                color = "#ff8099"
            else:
                color = "#80ff88"

        city_label = CTkLabel(
            master=table_frame,
            text=f"{city} at {time_of_day}",
            font=("Arial", 12),
            text_color=color,
        )
        city_label.grid(row=row_index, column=0, padx=10)

        safety_label = CTkLabel(
            master=table_frame, text=safety_level, font=("Arial", 12), text_color=color
        )
        safety_label.grid(row=row_index, column=1, padx=10)

        row_index += 1
    table_frame.pack(fill="both", expand=True)
    table_frame.place(relx=0.5, rely=0.45, anchor="center")

    unsafe_nodes, safe_nodes = unsafeCities(dep_city, arr_city, dep_time, G)
    primary_path, primary_time, alternate_path, alternate_time = ro.find_optimized_path(
        G, dep_city, arr_city, unsafe_nodes
    )
    primary_path_str = (
        f"Primary path: {primary_path} (Total Time: {primary_time} minutes)"
    )
    if alternate_path and len(primary_path) > 2:
        reroute_city = primary_path[1]
        primary_path_str += f"\nRerouted due to bad weather at {reroute_city} "

    label_primary_path = CTkLabel(
        master=RouteFrame,
        text=primary_path_str,
        font=("Arial", 13, "bold"),
        text_color="black",
    )
    label_primary_path.place(relx=0.02, rely=0.85, anchor="w")

    if alternate_path:
        alternate_path_str = (
            f"Rerouted path: {alternate_path} (Total Time: {alternate_time} minutes)"
        )
    else:
        alternate_path_str = "No Reroute needed"

    label_alternate_path = CTkLabel(
        master=RouteFrame,
        text=alternate_path_str,
        font=("Arial", 13, "bold"),
        text_color="black",
    )
    label_alternate_path.place(relx=0.02, rely=0.95, anchor="w")
    generate_map = CTkButton(
        master=RouteFrame,
        text="Map",
        text_color="white",
        fg_color="red",
        corner_radius=8,
        hover=True,
        hover_color="gray",
        command=lambda: ro.plot_graph(
            G, primary_path, alternate_path, dep_city, arr_city
        ),
        width=5,
    )

    generate_map.place(relx=0.9, rely=0.9, anchor="center")


In [17]:
def predictService(flightID, ServiceFrame):
    modelMapping = {
        "Airbus A319": 1,
        "Airbus A320": 2,
        "Boeing 777": 3,
        "Boeing 787": 4,
    }
    servicingData = pd.DataFrame(
        {
            "Days Since Servicing": [
                flights_df[flights_df["FlightID"] == flightID][
                    "Days_Since_Serving"
                ].values[0]
            ],
            "Warranty Status": [
                flights_df[flights_df["FlightID"] == flightID][
                    "Warranty_Status"
                ].values[0]
            ],
            "Days Since Purchase": [
                flights_df[flights_df["FlightID"] == flightID][
                    "Days_Since_Purchase"
                ].values[0]
            ],
            "Company": [
                modelMapping[
                    flights_df[flights_df["FlightID"] == flightID]["Model"].values[0]
                ]
            ],
        }
    )

    predictions = serviceModel.predict(servicingData)
    serviceStatus = predictions[0]
    service_status_label = CTkLabel(
        master=ServiceFrame,
        text=serviceStatus,
        font=("Arial", 14, "bold"),
        text_color="black",
        padx=20,
        pady=10,
    )
    service_status_label.place(relx=0.5, rely=0.90, anchor="center")
    return serviceStatus


In [18]:
def timeString(days):
    years = days // 365
    days %= 365
    months = days // 30
    days = days % 30
    years_text = f"{years:02} YEARS"
    months_text = f"{months:02} MONTHS"
    days_text = f"{days:02} DAYS"
    return years_text, months_text, days_text


In [19]:
def displayServiceFrame(flight_id, ServiceFrame):
    days_servicing = flights_df[flights_df["FlightID"] == flight_id][
        "Days_Since_Serving"
    ].values[0]
    days_servicing_label = CTkLabel(
        master=ServiceFrame,
        text="Time since servicing",
        font=("Arial", 14, "bold"),
        text_color="black",
        padx=20,
        pady=10,
    )
    days_servicing_label.place(relx=0.5, rely=0.2, anchor="center")
    years_service, months_service, days_service = timeString(days_servicing)

    service_years_label = CTkLabel(
        master=ServiceFrame,
        text=years_service,
        font=("Arial", 10, "bold"),
        fg_color="black",
        text_color="#80ff88",
        padx=20,
        pady=10,
    )
    service_months_label = CTkLabel(
        master=ServiceFrame,
        text=months_service,
        font=("Arial", 10, "bold"),
        fg_color="black",
        text_color="#80ff88",
        padx=20,
        pady=10,
    )
    service_days_label = CTkLabel(
        master=ServiceFrame,
        text=days_service,
        font=("Arial", 10, "bold"),
        fg_color="black",
        text_color="#80ff88",
        padx=20,
        pady=10,
    )
    service_years_label.place(relx=0.32, rely=0.275, anchor="center")
    service_months_label.place(relx=0.5, rely=0.275, anchor="center")
    service_days_label.place(relx=0.68, rely=0.275, anchor="center")

    last_purchase = flights_df[flights_df["FlightID"] == flight_id][
        "Days_Since_Purchase"
    ].values[0]

    years_purchase, months_purchase, days_purchase = timeString(last_purchase)
    days_purchasing_label = CTkLabel(
        master=ServiceFrame,
        text="Time since purchase",
        font=("Arial", 14, "bold"),
        text_color="black",
        padx=20,
        pady=10,
    )
    days_purchasing_label.place(relx=0.5, rely=0.375, anchor="center")
    service_years_label = CTkLabel(
        master=ServiceFrame,
        text=years_purchase,
        font=("Arial", 10, "bold"),
        fg_color="black",
        text_color="#80ff88",
        padx=20,
        pady=10,
    )
    service_months_label = CTkLabel(
        master=ServiceFrame,
        text=months_purchase,
        font=("Arial", 10, "bold"),
        fg_color="black",
        text_color="#80ff88",
        padx=20,
        pady=10,
    )
    service_days_label = CTkLabel(
        master=ServiceFrame,
        text=days_purchase,
        font=("Arial", 10, "bold"),
        fg_color="black",
        text_color="#80ff88",
        padx=20,
        pady=10,
    )
    service_years_label.place(relx=0.32, rely=0.45, anchor="center")
    service_months_label.place(relx=0.5, rely=0.45, anchor="center")
    service_days_label.place(relx=0.68, rely=0.45, anchor="center")

    model = flights_df[flights_df["FlightID"] == flight_id]["Model"].values[0]
    model_label = CTkLabel(
        master=ServiceFrame,
        text=f"Model: {model}",
        font=("Arial", 14, "bold"),
        text_color="black",
        padx=20,
        pady=10,
    )
    model_label.place(relx=0.5, rely=0.55, anchor="center")

    warranty_status = flights_df[flights_df["FlightID"] == flight_id][
        "Warranty_Status"
    ].values[0]
    if warranty_status:
        warranty_status = "Active"
    else:
        warranty_status = "Expired"
    warranty_status_label = CTkLabel(
        master=ServiceFrame,
        text=f"Warranty status: {warranty_status}",
        font=("Arial", 14, "bold"),
        text_color="black",
        padx=20,
        pady=10,
    )
    warranty_status_label.place(relx=0.5, rely=0.65, anchor="center")

    check_service_status = CTkButton(
        master=ServiceFrame,
        text="Check service status",
        text_color="white",
        fg_color="red",
        corner_radius=8,
        hover=True,
        hover_color="gray",
        command=lambda: predictService(flight_id, ServiceFrame),
    )
    check_service_status.place(relx=0.5, rely=0.80, anchor="center")


In [20]:
def get_flight_info():
    flight_id = combobox.get()
    if not flights_df[flights_df["FlightID"] == flight_id].empty:
        dep_city = flights_df[flights_df["FlightID"] == flight_id]["DEP_City"].values[0]
        dep_time = flights_df[flights_df["FlightID"] == flight_id]["Dep_Time"].values[0]
        arr_city = flights_df[flights_df["FlightID"] == flight_id]["ARR_City"].values[0]
        fuel_cap = flights_df[flights_df["FlightID"] == flight_id]["Fuel_Cap"].values[0]
        pass_cap = flights_df[flights_df["FlightID"] == flight_id]["Pass_Load"].values[0]

        info_window = CTk()
        info_window.geometry("1200x700")
        set_appearance_mode("light")

        # Create 3 frames for different information sections
        flightInfoFrame = CTkFrame(
            master=info_window, corner_radius=10, fg_color="#cfcfcf", width=1106
        )
        flightInfoFrame.pack(expand=True)
        flightInfoFrame.place(relx=0.5, rely=0.15, anchor="center")

        label_flght_id = CTkLabel(
            master=flightInfoFrame,
            text=f"Flight ID: {flight_id}",
            font=("Arial", 20, "bold"),
            text_color="black",
        )
        label_flght_id.place(relx=0.5, rely=0.15, anchor="center")

        label_dep_time = CTkLabel(
            master=flightInfoFrame,
            text=f"Departure time: {dep_time}",
            font=("Arial", 15),
            text_color="black",
        )
        label_dep_time.place(relx=0.5, rely=0.30, anchor="center")

        label_origin_2_destination = CTkLabel(
            master=flightInfoFrame,
            text=f"From: {dep_city} to {arr_city}",
            font=("Arial", 15),
            text_color="black",
        )
        label_origin_2_destination.place(relx=0.5, rely=0.45, anchor="center")

        label_fuel_capacity = CTkLabel(
            master=flightInfoFrame,
            text=f"Total fuel capacity: {fuel_cap}",
            font=("Arial", 15),
            text_color="black",
        )
        label_fuel_capacity.place(relx=0.5, rely=0.60, anchor="center")

        label_pass_load = CTkLabel(
            master=flightInfoFrame,
            text=f"Total passenger load: {pass_cap}",
            font=("Arial", 15),
            text_color="black",
        )
        label_pass_load.place(relx=0.5, rely=0.75, anchor="center")

        RouteFrame = CTkFrame(
            master=info_window,
            corner_radius=10,
            fg_color="#cfcfcf",
            width=550,
            height=400,
        )
        RouteFrame.pack(expand=True)
        RouteFrame.place(relx=0.27, rely=0.6, anchor="center")
        displaySafetyLevels(dep_city, dep_time, arr_city, RouteFrame)

        ServiceFrame = CTkFrame(
            master=info_window,
            corner_radius=10,
            fg_color="#cfcfcf",
            width=550,
            height=400,
        )
        ServiceFrame.pack(expand=True)
        ServiceFrame.place(relx=0.74, rely=0.6, anchor="center")
        displayServiceFrame(flight_id, ServiceFrame)

        info_window.mainloop()

    else:
        label_error = CTkLabel(
            master=app, text=f"", font=("Arial", 15), text_color="black"
        )
        label_error.place(relx=0.5, rely=0.85, anchor="center")
        label_error.configure(text="Invalid Flight ID. Please enter a valid Flight ID.")


In [21]:
app = CTk()
app.geometry("1200x700")
set_appearance_mode("light")
label_select_flight = CTkLabel(master=app, text="SELECT A FLIGHT", font = ("Arial", 25), text_color="black")
label_select_flight.place(relx=0.5, rely=0.4, anchor="center")
flight_ids = flights_df["FlightID"].tolist()
combobox = CTkComboBox(
    master=app,
    values=flight_ids,
    fg_color="white",
    border_color="black",
    corner_radius=5,
    dropdown_text_color="black",
    dropdown_font=CTkFont(size=14),
    hover=True,
    button_hover_color="lightgray",
    dropdown_hover_color="red",
)
get_info_button = CTkButton(
    master=app,
    text="Get Information",
    text_color="white",
    fg_color="red",
    corner_radius=8,
    hover=True,
    hover_color="gray",
    command=get_flight_info,  
)

get_info_button.place(relx=0.5, rely=0.6, anchor="center")

image_label = CTkLabel(master=app, text="")
image_label.place(relx=0.5,rely=0.5, anchor="center")
image_label.pack() 



combobox.place(relx=0.5, rely=0.5, anchor="center")
app.mainloop()
